### ISSUE TITLE
[QA] CLI Dashboard -> Sitemap - Shows the wrong no of frames on sitemap report landing page

### ISSUE THREAD

**Issue by kjnanda** [GoogleChromeLabs/ps-analysis-tool#313] opened 2023-11-30 13:34 UTC
1. Checkout the main branch from repo
2. Run `npm install`
3. Run `npm run cli:build`
4. Run `npm run cli -- -s https://rtcamp.com/sitemap_index.xml`
5. Open the report in browser
6. Observe that sitemap report shows wrong no frames on sitemap landing page as shown in the below screenshot.

<kbd>![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/bfcaa3b8-e590-4ab9-80a6-2a4e7c6b4950)</kbd>

**Comment by mayan-000** [comment] 2023-12-04 06:57
There seems to be confusion, it is not a bug.

The number shown on the sitemap's landing page is the unique count of frames we encountered across the sitemap.
Whereas @kjnanda is referring to sites(extracted from the sitemap) as frames on the sitemap's landing page, which forms a false negative case.

Closing this one as it's a false negative.

Thank you.

**Closed by mayan-000** 2023-12-04 06:57 UTC
Labels: bug, CLI
