### ISSUE TITLE
Wiki: Add a Settings section

### ISSUE THREAD

**Issue by maitreyie-chavan** [GoogleChromeLabs/ps-analysis-tool#310] opened 2023-11-30 07:46 UTC
## Task

**Description:**
Add information about the Settings field of the extension and the options it has in the Wiki's How-To section

<img width="771" alt="Screenshot 2023-11-30 at 1 15 45 PM" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/20221326/5d6a049f-8896-4607-988c-f06786bfc34d">

**Comment by actual-saurabh** [comment] 2023-12-01 06:53
The issue is really where to place this. The content isn't.

Here's the content:

```
By default, PSAT analyses only one tab at a time. This ensures minimum system usage. Otherwise, depending on hardware limitations and the total number of open tabs at a time, analysis can be resource intensive.

However, you can change this behaviour under **Settings > Total number of allowed tabs to be processed together:** and choose **No Restriction**

Screenshot 1 Settings, Default.

Screenshot 2 How to Reach Settings

Screenshot 2 Settings, Modified.

```

(That should be default for any screen manipulation instruction.

1. Screen Default. (Visualize Goal Screen)
2. How to Reach Screen. (Reach the Screen and match the vision, to instantly recognize success.)
3. Screen Modified. (Visualize Goal Screen, Manipulate their screen to match this screen, Instantly recognize success, even before they hit save.)

Let me continue working on #207 and when I have a set place for this, we can close this.

**Comment by fellyph** [comment] 2023-12-04 09:28
@actual-saurabh We can add this content at https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/A.-PSAT's-How-To#installing-from-chrome-web-store

**Comment by fellyph** [comment] 2023-12-08 11:05
@maitreyie-chavan, can we close this issue once the new page is included?

**Comment by maitreyie-chavan** [comment] 2023-12-08 13:47
@fellyph Yes, it can be added for now. As we were restructuring the How-To in the Wiki, we can revisit this section and update the content if needed.

No further updates to be made to the Wiki apart from this section. 🙇🏻‍♀️

**Closed** 2023-12-26 17:51 UTC
Labels: documentation
