### ISSUE TITLE
[QA] Error and Disappearance of Frame Overlay icon

### ISSUE THREAD

**Issue by kjnanda** [GoogleChromeLabs/ps-analysis-tool#355] opened 2023-12-21 07:12 UTC
**Describe the bug**
Clicking on the Frame overlay icon throws error on the chrome://extension page. 

The extension displays errors, particularly when switching tabs where extension use is restricted. Additionally, the Frame overlay icon disappears and can only be restored through a page refresh. 

It is mandatory to address this issue and implement a robust workaround to prevent these errors from occurring.

**To Reproduce**

- Open a new page page
- Open PSAT extension from DevTools
- Click on Frame Overlay Icon from the sidebar 
- Switch to next tab without entering URL or switch to the chrome://extensions page
- Observe the errors
- Now, go back to the tab where the page was analysed and observe the `Frame overlay icon` is not present
- Refresh the page to restore the icon back 

**Expected behavior**
There should not be any errors on chrome://extension page not the icon should disappear.

**Screenshots**

<kbd><img width="688" alt="Screenshot 2023-12-21 at 12 39 00" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/683c6ccd-1faa-4ed3-acca-0d7addd8a903"></kbd>

**Visual**

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/6857164d-268e-42b5-b231-b4db6d9a7dcf

**Desktop (please complete the following information):**
 - OS: MAC 13.5.2 (22G91)
 - Chrome  Browser Version 120.0.6099.109 (Official Build) (arm64)
 - PSAT - Latest code from Dev branch [173f2d1e5f3e004ae3410ee6f3383c7c7c332cc2]

**Comment by kjnanda** [comment] 2024-02-08 10:49
@maitreyie-chavan Please change the milestone for this issue. This has not been addressed as part of V0.5.0

**Comment by pavanpatil1** [comment] 2024-02-09 09:45
Cross-verified the issue with the V0.5.0 and not able to reproduce this issue. 

[frame.webm](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/44057535/49b92ea1-1043-414c-a093-317faf87fed6)

**Comment by maitreyie-chavan** [comment] 2024-02-09 10:26
Addressed and released as a part of [v0.5](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.5.0)

**Closed by maitreyie-chavan** 2024-02-09 10:26 UTC
Labels: bug, PSAT
